# NumPy

**NumpPy** significa **Numerical Python**, es una librería (paquete) que permite trabajar con grandes cantidades
de datos numéricos de forma fácil y muy eficiente.  
Con ella podréis construir vectores, matrices y tensores empleando `np.array`.

La documentación, que está muy bien, la puedes encontrar en https://numpy.org.

## 0. Lo primero es importar el paquete
Tras importarlo, podrás usar su funcionalidad a través de `np.lo_que_sea`.

In [1]:
import numpy as np

---
## 1. Introducción

#### Ejercicio
- Crea un `np.array` con `lista_py`.
- Suma 10 a todos los elementos de la lista.
- Suma 10 a todos los elementos del array.

In [2]:
lista_py = [ 7, 2, 4, 1, 3 ]

lista_py

[7, 2, 4, 1, 3]

In [3]:
# usando list comprehension

lista2 = [ x + 10 for x in lista_py ]

lista2

[17, 12, 14, 11, 13]

In [4]:
# usando un bucle

lista3 = []

for numero in lista_py:
  lista3.append(numero + 10)

lista3

[17, 12, 14, 11, 13]

In [5]:
# creo array en numpy

lista_np = np.array(lista_py)

lista_np

array([7, 2, 4, 1, 3])

In [6]:
# usando numpy!

lista_np + 10

array([17, 12, 14, 11, 13])

#### Ejercicio
- Calcula la media de la lista.
- Calcula la media del array.

In [7]:
# calculo media en python con un bucle

def media(lista):

  N = len(lista)
  acumulado = 0
  for numero in lista:
    acumulado = acumulado + numero

  return acumulado / N

media(lista_py)

3.4

In [8]:
# otra forma

def media(lista):
    return sum(lista) / len(lista)

In [9]:
# usando numpy!

np.mean(lista_np)

3.4

---
## Arrays de NumPy

#### Ejercicio
Crea los siguientes arrays:
- Un array que contenga 8 ceros.
- Un array que contenga 5 unos.
- Un array cuyos elementos vayan desde el 1 al 10, incrementando de uno en uno.
- Un array con 11 elementos, cuyos valores empiecen en 0 y acaben en 5.

In [10]:
ceros = np.zeros(8)

ceros

array([0., 0., 0., 0., 0., 0., 0., 0.])

In [11]:
unos = np.ones(5)

unos

array([1., 1., 1., 1., 1.])

In [12]:
rango = np.arange(1, 11)

rango

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
lineal = np.linspace(0,5, 11)

lineal

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

---
## Exploremos más operaciones básicas

#### Ejercicio

Para el array de `edades`, calcula lo siguiente:

- media.
- mediana.
- desviación típica.
- máximo
- mínimo.
- Imprime los valores mayores de 18.
- Selecciona las tres primeras edades (por la izquierda).
- Selecciona las tres últimas (por la derecha).

In [14]:
edades = [ 15, 56, 33, 12, 21, 53, 7, 32, 8, 45, 66, 4 ]

In [15]:
edades_np = np.array(edades)

In [16]:
np.mean(edades_np)

29.333333333333332

In [17]:
np.median(edades_np)

26.5

In [18]:
np.std(edades_np)

20.51963829007606

In [19]:
np.max(edades_np)

66

In [20]:
np.min(edades_np)

4

In [21]:
edades_np [ edades_np > 18 ]

array([56, 33, 21, 53, 32, 45, 66])

In [22]:
edades_np[:3]

array([15, 56, 33])

In [23]:
edades_np[-3:]

array([45, 66,  4])

---
## Vectorización

#### Ejercicio

Vamos a calcular el siguiente ratio financiero a partir de datos trimestrales:

$$\frac{EV}{EBIDTA}=\frac{Capitalizacion\ De\ Mercado + Deuda\ Total - Caja\ y\ Equivalentes}{EBITDA}$$

In [24]:
market_cap = [ 1100, 1200, 1050, 1200 ]
debt       = [  100,  100,  110,  110 ]
cash       = [   23,   17,   21,   15 ]
ebitda     = [  107,  121,  113,   99 ]

In [25]:
market_cap_np = np.array(market_cap)
debt_np       = np.array(debt)
cash_np       = np.array(cash)
ebitda_np     = np.array(ebitda)

ratio = (market_cap_np + debt_np - cash_np) / ebitda_np

ratio

array([11.        , 10.60330579, 10.07964602, 13.08080808])

---
## Slicing

#### Ejercicio

Dada la siguiente lista de `precios` anuales:
- Recupera los 3 primeros.
- Recupera los 3 últimos.
- Dale la vuelta (que empiece por último elemento y acabe en el primero).
- Calcula los `retornos` anuales:

$$R_t = \frac{ p_t - p_{t-1}}{p_{t-1}}$$

In [26]:
precios = [ 95.7, 105.1, 101.7, 107.0, 93.9, 100.9, 105.9, 108.1, 100.4, 105.1 ]

In [27]:
precios[:3]

[95.7, 105.1, 101.7]

In [28]:
precios[-3:]

[108.1, 100.4, 105.1]

In [29]:
precios[::-1]

[105.1, 100.4, 108.1, 105.9, 100.9, 93.9, 107.0, 101.7, 105.1, 95.7]

In [30]:
precios_np = np.array(precios)

# No podemos calcular el primer retorno (sería la posición 0) ya que el "t-1" no está definido.
# Así que siguientes retornos son empezando en el segundo día.
retornos = (precios_np[1:] - precios_np[:-1]) / precios_np[:-1]
retornos

array([ 0.09822362, -0.03235014,  0.05211406, -0.12242991,  0.07454739,
        0.04955401,  0.02077432, -0.07123034,  0.04681275])

---
## Números aleatorios

#### Ejercicio
Genera 5 números aleatorios enteros entre 0 y 100.

In [31]:
np.random.randint(0, 100+1, 5)

array([76, 76, 81, 82, 98])

#### Ejercicio
El peso de los estudiantes de Comillas se distribuye como la siguiente normal: $Peso \sim \mathcal{N}(\mu=50, \sigma=10)$.

Genera 10 medidas de peso aleatorias que sigan dicha distribución. Recuerda:

$$\frac{Peso - \mu}{\sigma} \sim \mathcal{N}(0, 1)$$

In [32]:
normal = np.random.randn(10)
pesos = 10*normal + 50

pesos

array([43.2129322 , 46.95577544, 34.9779394 , 54.98827637, 45.90914518,
       43.82112678, 51.23962375, 53.09857411, 54.70631155, 48.32990847])

---
---
## Matrices

#### Ejercicio

Crea una matriz de numpy a partir de esta lista de listas:

In [33]:
datos = [ [ 1, 2, 3],
          [ 4, 5, 6],
          [ 7, 8, 9] ]

In [34]:
datos_np = np.array(datos)

datos_np

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### Ejercicio
Imprime `shape`, `size`, `ndim`de la matriz anterior.

In [35]:
datos_np.shape

(3, 3)

In [36]:
datos_np.size

9

In [37]:
datos_np.ndim

2

#### Ejercicio
Crea las siguientes matrices **4x4**:
- Todo ceros.
- Todo unos.
- Matriz identidad (diagonal a 1, resto a 0).

In [38]:
np.zeros((4,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [39]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [40]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---
## Operaciones con matrices

#### Ejercicio
Para la matriz `A`, calcula lo siguiente:
- La suma de las filas.
- La suma de las columnas.
- Extrae la diagonal.

In [41]:
A = [ [ 7, 4, 3, 2, 6, 6, 7, 0 ],
      [ 4, 4, 4, 4, 7, 1, 4, 3 ],
      [ 2, 7, 4, 8, 9, 4, 3, 5 ],
      [ 0, 9, 7, 1, 8, 0, 5, 4 ],
      [ 8, 1, 4, 1, 5, 7, 1, 6 ],
      [ 2, 6, 4, 2, 8, 9, 3, 4 ],
      [ 6, 7, 0, 3, 8, 1, 1, 7 ],
      [ 8, 4, 1, 6, 7, 2, 0, 4 ] ]

In [42]:
a = np.array(A)

np.sum(a, axis=1)

array([35, 31, 42, 34, 33, 38, 33, 32])

In [43]:
np.sum(a, axis=0)

array([37, 42, 27, 27, 58, 30, 24, 33])

In [44]:
np.diag(a)

array([7, 4, 4, 1, 5, 9, 1, 4])

#### Ejercicio

Calcula el determinante y la inversa de la matriz `B` y comprueba que el resultado es correcto, es decir, que $[B] \times [B]^{-1} = [I]$

In [45]:
B = [ [ 1, -1,  1 ],
      [ 0,  2, -1 ],
      [ 2,  3,  0 ] ]

In [46]:
b = np.array(B)

b

array([[ 1, -1,  1],
       [ 0,  2, -1],
       [ 2,  3,  0]])

In [47]:
np.linalg.det(b)

1.0

In [48]:
b_inv = np.linalg.inv(b)
b_inv

array([[ 3.,  3., -1.],
       [-2., -2.,  1.],
       [-4., -5.,  2.]])

In [49]:
resultado = b @ b_inv
resultado

array([[ 1.0000000e+00,  8.8817842e-16, -4.4408921e-16],
       [ 0.0000000e+00,  1.0000000e+00,  0.0000000e+00],
       [ 4.4408921e-16,  4.4408921e-16,  1.0000000e+00]])

In [50]:
# el mismo resultado, pero redondeado para que sea más fácil de leer
np.round(resultado)

array([[ 1.,  0., -0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

#### Ejercicio
Calcula la traspuesta de `B`.

In [51]:
b

array([[ 1, -1,  1],
       [ 0,  2, -1],
       [ 2,  3,  0]])

In [52]:
b.T

array([[ 1,  0,  2],
       [-1,  2,  3],
       [ 1, -1,  0]])

#### Ejercicio
Multiplica `B` por 3 y suma al resultado la matriz `C`. Guarda el resultado en la matriz `D`:

$$[D] = 3 \times [B] + [C]$$

In [53]:
C = [ [  0,  -1,  1 ],
      [ -1,   0, -1 ],
      [  1,  -1,  0 ] ]

In [54]:
c = np.array(C)

In [55]:
3 * b + c

array([[ 3, -4,  4],
       [-1,  6, -4],
       [ 7,  8,  0]])

#### Ejercicio

Cambia la forma de la matriz `A` (**8x8** elementos) para que sea una matriz **4x16**.

In [56]:
a.reshape((4,16))

array([[7, 4, 3, 2, 6, 6, 7, 0, 4, 4, 4, 4, 7, 1, 4, 3],
       [2, 7, 4, 8, 9, 4, 3, 5, 0, 9, 7, 1, 8, 0, 5, 4],
       [8, 1, 4, 1, 5, 7, 1, 6, 2, 6, 4, 2, 8, 9, 3, 4],
       [6, 7, 0, 3, 8, 1, 1, 7, 8, 4, 1, 6, 7, 2, 0, 4]])

---
---
## Markowitz

Vamos a convertirnos en expertos en gestión de carteras de inversión:

- El **retorno esperado** de una cartera:

$$E(r_p) = \sum_{i=1}^n{w_i E(r_i)}$$

- La **volatilidad**  de una cartera:

$$\sigma_p^2 = \sum_{i=1}^n \sum_{j=1}^n {w_i w_j \sigma_i \sigma_j \rho_{ij}}$$

Y ahora, esas mismas expresiones en forma matricial (que es lo que usaremos en **numpy**):

$$E(r_p) = \vec w_i \cdot \vec R_i$$

$$\sigma_p^2 = \vec w_i \cdot \left[ \sigma_{ij} \right] \cdot {\vec w_i}^T$$


#### Ejercicio

Calcula el retorno y la volatilidad de una cartera, dados los pesos de cada activo, su rentabilidad y la matriz de covarianzas.

In [57]:
retorno_anual_activos = [ 0.10, 0.05, 0.07 ]

pesos_activos         = [ 0.20, 0.40, 0.40 ]

covarianza_activos    = [ [ 0.05,  0.01,  0.02 ],
                          [ 0.01,  0.07, -0.03 ],
                          [ 0.02, -0.03,  0.03 ] ]

In [58]:
r_i    = np.array(retorno_anual_activos)
w_i    = np.array(pesos_activos)
cov_ij = np.array(covarianza_activos)

In [59]:
retorno_cartera = w_i @ r_i
retorno_cartera

0.06800000000000002

In [60]:
volatilidad_cartera = np.sqrt( w_i @ cov_ij @ w_i.T )
volatilidad_cartera

0.11489125293076059

---
---
## Ejercicios Hoja A

#### 1. Cálculo del Total de Ventas Semanales
Dado un array que representa las
ventas diarias de un producto durante una semana, calcula el total de ventas de
la semana.

In [61]:
ventas = [542, 540, 633, 682, 570, 982, 864]

In [62]:
ventas_np = np.array(ventas)

np.sum(ventas_np)

4813

#### 2. Ajuste de Precios de Productos
Dado un array que contiene los precios de 7
productos, aplica un aumento del 8% debido a un cambio en los costes de
producción y muestra el nuevo array de precios.

In [63]:
precios = [830, 908, 511, 745, 892, 427, 344]

In [64]:
precios_np = np.array(precios)

precios_finales = precios_np * 1.08

precios_finales

array([896.4 , 980.64, 551.88, 804.6 , 963.36, 461.16, 371.52])

#### 3. Identificación de Tiendas con Menores Ventas
Dado un array que contiene
las ventas de un producto en 12 tiendas, identifica la tienda con la menor venta
utilizando `np.argmin()`.

In [65]:
tiendas = [293, 846, 156, 767, 840, 394, 415, 815, 372, 758, 464, 615]

In [66]:
tiendas_np = np.array(tiendas)

np.argmax(tiendas_np)

1

#### 4. Distribución de Comisiones

Dado un array que representa las ventas de 8
vendedores, aplica una comisión del 5% sobre las ventas y muestra las
comisiones para cada vendedor.

In [67]:
ventas = [60007, 74329, 79758, 77345, 55553, 98266, 96792, 80302]

In [68]:
ventas_np = np.array(ventas)

comision = ventas_np * 0.05

comision

array([3000.35, 3716.45, 3987.9 , 3867.25, 2777.65, 4913.3 , 4839.6 ,
       4015.1 ])

#### 5. Comparación de Rendimiento de Marketing

Tienes dos matrices que
representan las ventas mensuales de 3 productos durante un año en dos
campañas de marketing diferentes. Suma las matrices para obtener las ventas
totales por producto en ambas campañas y calcula el porcentaje de cada campaña por producto.

In [69]:
campaign_a = [ [ 460, 745, 883, 209, 517, 289, 408, 636, 580, 819, 187, 705 ],
               [ 250, 660, 210, 467, 643, 617,  59, 371, 396, 144, 831, 833 ],
               [ 559, 871, 153, 178, 687, 387, 837, 989, 971, 640, 929, 151 ] ]

campaign_b = [ [ 402, 171, 283, 887, 155, 627, 727, 608, 502, 705, 108, 358 ],
               [ 898, 338, 834, 872, 267, 586, 489, 877, 520, 630, 169, 304 ],
               [ 248, 404, 794, 583, 706, 282, 521, 621, 712, 576, 442, 655 ] ]

In [70]:
a = np.array(campaign_a)
b = np.array(campaign_b)

In [71]:
# calculamos total de ventas por producto en campaña A
sum_a = np.sum(a, axis=1)
sum_a

array([6438, 5481, 7352])

In [72]:
# calculamos total de ventas por producto en campaña B
sum_b = np.sum(b, axis=1)
sum_b

array([5533, 6784, 6544])

In [73]:
# calculamos el total de las ventas, incluyendo ambas campañas
sum_total = sum_a + sum_b
sum_total

array([11971, 12265, 13896])

In [74]:
# porcentaje por producto que representan las ventas en la campaña A sobre el total
sum_a / sum_total

array([0.53779968, 0.44688137, 0.52907311])

In [75]:
# porcentaje por producto que representan las ventas en la campaña B sobre el total
sum_b / sum_total

array([0.46220032, 0.55311863, 0.47092689])

#### 6. Gestión de Inventario en Almacenes

Dada una matriz que representa el
inventario de 6 productos en 4 almacenes, calcula el inventario total de cada
producto sumando los inventarios de todos los almacenes.

In [76]:
inventory = [ [  2,  5, 12, 10 ],
              [ 10, 19,  1, 12 ],
              [  9,  7, 17,  5 ],
              [ 19, 12, 16,  8 ],
              [  3,  6,  4, 13 ],
              [ 12, 14,  4,  5 ] ]

In [77]:
inventory_np = np.array(inventory)

In [78]:
# Inventario total por producto
np.sum(inventory, axis=1)

array([29, 42, 38, 55, 26, 35])

#### 7. Análisis de Precios con Descuentos
Dado un tensor que contiene los precios
de 5 productos en 4 tiendas durante 3 meses, aplica un descuento del 15% y
calcula el precio promedio por producto en todas las tiendas y meses.

In [79]:
precios = [ [ [ 12, 13, 14, 13, 12 ],
              [ 12, 18, 13, 13, 17 ],
              [ 12, 18, 10, 11, 16 ],
              [ 12, 19, 17, 10, 12 ] ],

            [ [ 18, 15, 14, 19, 19 ],
              [ 10, 14, 15, 17, 12 ],
              [ 18, 16, 19, 15, 19 ],
              [ 15, 14, 18, 13, 11 ] ],

            [ [ 10, 15, 10, 19, 14 ],
              [ 19, 16, 18, 17, 19 ],
              [ 12, 12, 18, 14, 10 ],
              [ 16, 11, 19, 15, 16 ] ] ]

In [80]:
precios_np = np.array(precios)

In [81]:
desc_precios = precios_np * 0.85

In [82]:
# precio promedio por producto (horizontal) y tienda (vertical)
np.mean(desc_precios, axis=0)

array([[11.33333333, 12.18333333, 10.76666667, 14.45      , 12.75      ],
       [11.61666667, 13.6       , 13.03333333, 13.31666667, 13.6       ],
       [11.9       , 13.03333333, 13.31666667, 11.33333333, 12.75      ],
       [12.18333333, 12.46666667, 15.3       , 10.76666667, 11.05      ]])

In [83]:
# precio promedio por producto (horizontal) y mes (vertical)
np.mean(desc_precios, axis=1)

array([[10.2   , 14.45  , 11.475 ,  9.9875, 12.1125],
       [12.9625, 12.5375, 14.025 , 13.6   , 12.9625],
       [12.1125, 11.475 , 13.8125, 13.8125, 12.5375]])

In [84]:
# precio promedio por tienda (horizontal) y mes (vertical)
np.mean(desc_precios, axis=2)

array([[10.88, 12.41, 11.39, 11.9 ],
       [14.45, 11.56, 14.79, 12.07],
       [11.56, 15.13, 11.22, 13.09]])

#### 8. Evaluación de Rentabilidad Anual por Producto
Dados dos tensores 3D que
representan los ingresos y costes de 5 productos en 4 regiones durante 3 años
(dimensiones: 3x4x5), calcula la rentabilidad anual para cada producto en cada
región.

In [85]:
ingresos = [ [ [ 117, 115, 116, 117, 118 ],
               [ 119, 117, 117, 116, 117 ],
               [ 110, 117, 119, 118, 119 ],
               [ 110, 118, 117, 111, 110 ] ],

             [ [ 117, 116, 119, 115, 110 ],
               [ 117, 115, 111, 113, 116 ],
               [ 118, 118, 112, 110, 118 ],
               [ 119, 117, 112, 115, 111 ] ],

             [ [ 118, 110, 114, 118, 110 ],
               [ 117, 110, 113, 117, 118 ],
               [ 117, 114, 114, 113, 114 ],
               [ 111, 118, 113, 115, 118 ] ] ]

costes = [ [ [ 69, 67, 62, 60, 62 ],
             [ 61, 67, 66, 65, 68 ],
             [ 67, 65, 60, 68, 64 ],
             [ 67, 68, 63, 65, 69 ] ],

           [ [ 65, 63, 69, 61, 67 ],
             [ 69, 62, 62, 62, 61 ],
             [ 63, 67, 62, 69, 69 ],
             [ 67, 67, 62, 69, 67 ] ],

           [ [ 66, 68, 68, 63, 68 ],
             [ 64, 61, 67, 65, 63 ],
             [ 66, 69, 65, 68, 66 ],
             [ 67, 67, 60, 61, 64 ] ] ]

In [86]:
ingresos_np = np.array(ingresos)
costes_np   = np.array(costes)

beneficio_np = ingresos_np - costes_np

In [87]:
rentabilidad_np = beneficio_np / costes_np

In [88]:
# rentabilidad media anual por producto (horizontal) y región (vertical)
np.mean(rentabilidad_np, axis=0)

array([[0.76117699, 0.7251116 , 0.75735867, 0.90275392, 0.72088797],
       [0.82486562, 0.80146202, 0.74987234, 0.80239868, 0.83174782],
       [0.7625114 , 0.73778931, 0.84787703, 0.66375391, 0.76559755],
       [0.69154229, 0.7475856 , 0.84897593, 0.75320163, 0.69822311]])

---
---
## Otros ejemplos

#### 9. Sucursales

Una empresa tiene 5 sucursales, y cada sucursal tiene un registro mensual de ventas durante los últimos 12 meses. Se te proporciona la información de las ventas de cada sucursal en un array de NumPy.

- Calcula el total de ventas por sucursal.
- Calcula el promedio de ventas mensual para cada sucursal.
- Identifica el mes con la mayor venta en cada sucursal.
- Calcula las ventas totales de todas las sucursales por mes.
- Encuentra las sucursales que tuvieron al menos un mes con ventas por encima de 90,000.
- Calcula el crecimiento porcentual de las ventas en cada sucursal comparando el primer mes y el último.

In [89]:
sucursales = [ [ 45000, 48000, 52000, 58000, 60000, 62000, 65000, 63000, 70000, 75000, 78000, 80000 ],
               [ 55000, 53000, 57000, 59000, 61000, 64000, 66000, 68000, 71000, 76000, 80000, 85000 ],
               [ 47000, 46000, 49000, 50000, 54000, 55000, 56000, 58000, 59000, 62000, 64000, 67000 ],
               [ 60000, 62000, 63000, 65000, 67000, 70000, 73000, 75000, 77000, 80000, 82000, 85000 ],
               [ 51000, 53000, 56000, 58000, 60000, 63000, 65000, 68000, 71000, 75000, 77000, 79000 ] ]

In [90]:
sucursales_np = np.array(sucursales)

In [91]:
# ventas totales por sucursal
np.sum(sucursales_np, axis=1)

array([756000, 795000, 667000, 859000, 776000])

In [92]:
# promedio de ventas por sucursal
np.mean(sucursales_np, axis=1)

array([63000.        , 66250.        , 55583.33333333, 71583.33333333,
       64666.66666667])

In [93]:
# sumamos uno para empezar a contar los meses en 1 y no en 0
np.argmax(sucursales_np, axis=1) + 1

array([12, 12, 12, 12, 12])

In [94]:
# ventas totales por mes
np.sum(sucursales_np, axis=0)

array([258000, 262000, 277000, 290000, 302000, 314000, 325000, 332000,
       348000, 368000, 381000, 396000])

In [95]:
ultimo  = sucursales_np[:,-1]
primero = sucursales_np[:, 0]

rentabilidad = (ultimo - primero) / primero

rentabilidad

array([0.77777778, 0.54545455, 0.42553191, 0.41666667, 0.54901961])

#### 10. Predicción de precios
Dada una serie de `precios` históricos, estima el siguiente valor de la serie empleando un modelo de regresión lineal:

$$Y_i = \alpha + \beta \times X_i$$

Que en nuestro caso quedaría así, donde `t` es la posición en el array:

$$precios_t = \alpha + \beta \times t$$

Si la serie temporal tiene `T` observaciones, tienes que:
- Calcular $\alpha$.
- Calcular $\beta$.
- Estimar el siguiente precio, el que está en la posición `T` (recuerda que en Python se empieza a contar en 0).

Como ayuda puedes emplear estas fórmulas:

$$\beta = \frac{\sum (X_i - \bar X)(Y_i - \bar Y)}{\sum (X_i - \bar X)^2}$$
$$\alpha = \bar Y - \beta \bar X$$

Donde $\bar X$ y $\bar Y$ son las medias.

In [96]:
def prediccion(serie):

    n = len(serie)

    x = np.arange(n)
    y = np.array(serie)
    mean_x = np.mean(x)
    mean_y = np.mean(y)

    beta = np.sum((x - mean_x) * (y - mean_y)) / np.sum((x - mean_x)**2)
    alpha = mean_y - beta * mean_x
    
    forecast = alpha + beta * n

    #print(f'{alpha=:.3} {beta=:.3} {forecast=:.3}')

    return forecast

In [97]:
serie = [1, 2, 3, 4]

prediccion(serie)

5.0